"""create_initial_tables

Revision ID: 3c00a9c8b196
Revises: 
Create Date: 2026-05-27 14:46:34.412831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c00a9c8b196'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trigger_metric', sa.String(length=128), nullable=False),
    sa.Column('agent_diagnosis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_action', sa.String(length=64), nullable=True),
    sa.Column('human_decision', sa.String(length=32), nullable=True),
    sa.Column('reasoning_trace', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_opened_at'), 'incidents', ['opened_at'], unique=False)
    op.create_table('monitoring_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('feature_name', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_metrics_timestamp'), 'monitoring_metrics', ['timestamp'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('input_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prediction', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_timestamp'), 'predictions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_timestamp'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_monitoring_metrics_timestamp'), table_name='monitoring_metrics')
    op.drop_table('monitoring_metrics')
    op.drop_index(op.f('ix_incidents_opened_at'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
